basic:
  verbose: 1
  master: 127.0.0.1
  cloud: 192.168.1.100
device:
  module:
    use_base: false
    use_arm: true
    use_operator: true
    use_cannula: false
  beckhoff:
    address: 127.0.0.1
    port: 851
